---
name: Diff Check
description: An Action which runs a command and fails if it changes anything.
inputs:
  command:
    description: Command to run
    required: true
  message:
    description: "Message to show when failing (e.g.: explaining what to do)"
    default: "has changed"
runs:
  using: "composite"
  steps:
    - run: ${{ inputs.command }}
      shell: bash
    - run: |
        if [ ! "$(git diff-index --quiet HEAD --)" ]; then
          for n in $(git diff --name-only); do
            echo "::error file=$n::$n ${{ inputs.message }}"
          done
          exit 1
        fi
      shell: bash
